name: "Hello Actions"
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        required: true
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello action
        run: echo "Hello User ${{ github.event.inputs.name }}"
