name: "Hello Actions"
description: "Greet someone"
author: "Preethi"
on:
  work_dispatch:
    inputs:
      MY_NAME:
        description: "Who to greet"
        required: true
        default: "World"

  runs:
    uses: "docker"
    image: "Dockerfile"

  branding:
    icon: "mic"
    color: "purple"
