name: "Hello Actions"
permissions: "Greet someone"

on:
  workflow_dispatch:
    inputs:
      MY_NAME:
        description: "Who to greet"
        required: true
        default: "World"

    runs:
      uses: "docker"
      image: "Dockerfile"

    branding:
      icon: "mic"
      color: "purple"
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello action
        run: echo "Hello ${{ github.event.inputs.MY_NAME }}"
